// scraped from georgopoulos.com.gr on 2026-05-08
window.SCRAPED_BENTWOOD_PIETRO = [
  {
    id: 'bw-v63',
    name: 'Bentwood V63',
    images: [
      'https://static.wixstatic.com/media/fae23e_6a20cc3bcd1b408c8720869d76ce48a1~mv2.png',
      'https://static.wixstatic.com/media/fae23e_988884b873f746ed924ed5370c920a72~mv2.png',
      'https://static.wixstatic.com/media/fae23e_32c376b315914cb6a09d9b773adadc31~mv2.png',
      'https://static.wixstatic.com/media/fae23e_de1698c8d5254b00b9a04659e16aeee8~mv2.png',
      'https://static.wixstatic.com/media/fae23e_42dfcbe2ed3642f1b80e58078a6960a1~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_4b4eefb730c14b9396f8845d8fd422e0~mv2.jpg',
    ],
    description_gr: 'Μύλος κάθετης κοπής με επίπεδα μαχαίρια 63mm με μοναδική γεωμετρία. Απόδοση εξαιρετικής γεύσης ανεξαρτήτως επιπέδου άλεσης.',
    description_en: 'Vertical cutting grinder featuring 63mm flat burrs with unique geometry, delivering exceptional flavor regardless of grind setting.',
    specs: {
      burr_mm: '63',
      burr_type: 'flat',
      rpm: '1400',
      hopper_capacity_g: '600',
      power_w: '660',
      weight_kg: '21',
      dimensions: '198 × 415 × 570 mm',
      country: null,
      special_features: 'Dual cooling system, low retention, removable/non-removable portafilter base, anti-oxidation hopper seal, included cleaning brush',
    },
    source_url: 'https://www.georgopoulos.com.gr/μύλος-άλεσης-καφέ-bentwoodv63',
    status: 'ok',
  },
  {
    id: 'bw-h75',
    name: 'Bentwood H75',
    images: [
      'https://static.wixstatic.com/media/fae23e_e37b5da7149e4a38b7fc446138180d44~mv2.png',
      'https://static.wixstatic.com/media/fae23e_a62354064d694fa0ab4fbfe1f45afa03~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_6b153d0905294d878e83434a848c2dc2~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_e49d8e7b8b6f49df87170d57209c621d~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_15e0a8795e6148c0869e6d403c6be89b~mv2.png',
    ],
    description_gr: 'Ηλεκτρονικός μύλος άλεσης On Demand με επίπεδα μαχαίρια blind 75mm με μοναδική γεωμετρία, με σύστημα άλεσης βάσει βάρους και αυτόματη παραμετροποίηση επιπέδου.',
    description_en: 'Electronic on-demand grinder featuring 75mm flat burrs with unique geometry. Offers weight-based grinding (0.1g precision), automatic fineness adjustment, and multiple operation modes including time-based and barista functions.',
    specs: {
      burr_mm: '75',
      burr_type: 'flat',
      rpm: null,
      hopper_capacity_g: null,
      power_w: null,
      weight_kg: null,
      dimensions: '170 × 300 × 440 mm',
      country: null,
      grinding_speed: '7 g/s (espresso)',
      special_features: 'Precision Scale Grinding technology; near-silent operation; weight-based grinding (±0.1g accuracy); three operation modes (weight, time, barista)',
    },
    source_url: 'https://www.georgopoulos.com.gr/μύλος-άλεσης-καφέ-bentwoodvh75',
    status: 'ok',
  },
  {
    id: 'pt-pietro',
    name: 'Pietro',
    images: [
      'https://static.wixstatic.com/media/fae23e_4e1f22c432b84c5b9d98167e4a083c8b~mv2.png',
      'https://static.wixstatic.com/media/fae23e_ae090d5cd86649c3b848a58745735b4e~mv2.png',
    ],
    description_gr: 'Η επανάσταση στους μύλους κάθετης κοπής! Πρωτοποριακός σχεδιασμός και τεχνολογική υπεροχή για καφέ με υπογραφή.',
    description_en: 'A revolutionary vertical-cut grinder featuring pioneering design and technological excellence for signature coffee preparation.',
    specs: {
      burr_mm: '58',
      burr_type: 'flat',
      rpm: null,
      hopper_capacity_g: null,
      power_w: null,
      weight_kg: null,
      dimensions: null,
      country: null,
      special_features: 'Vertical cutting configuration, ergonomic geometry, multiple color options, manual operation, espresso-to-filter grind range',
    },
    source_url: 'https://www.georgopoulos.com.gr/pietrogrinders',
    status: 'ok',
  },
];
