// scraped from georgopoulos.com.gr on 2026-05-08
window.SCRAPED_BRITA = [
  {
    id: 'br-aquagusto',
    name: 'BRITA Aqua Gusto',
    image: 'https://static.wixstatic.com/media/fae23e_435729da056d4b10a1d623021860b630~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/bff2ed_869fd900f5bb40d3a87ba2a8c30731ef~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_435729da056d4b10a1d623021860b630~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_a49192621fd44be7884d52f8b395ce21~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_60eea4c9c9f54425aa75446423a3cb3b~mv2.png',
    ],
    description_gr: 'Το Brita Aqua Gusto αποτελεί την πλέον πρακτική λύση φίλτρανσης για μηχανές καφέ με δοχείο νερού.',
    description_en: 'The Brita Aqua Gusto represents the most practical water filtration solution for coffee machines with water reservoirs. Engineered to enhance coffee taste, aroma, and appearance while combating water hardness that creates salt deposits in coffee equipment.',
    specs: {
      filter_type: 'Carbon',
      capacity_m3: null,
      compatible: 'Coffee machines with water reservoirs (all tanks, no adapter required)',
      cartridge_sizes: ['100', '250'],
      duration: '6 months',
      max_pressure_bar: null,
    },
    source_url: 'https://www.georgopoulos.com.gr/a-gusto',
    status: 'ok',
  },
  {
    id: 'br-aquaaroma',
    name: 'BRITA Aqua Aroma Crema',
    image: 'https://static.wixstatic.com/media/fae23e_7add601d116441f682e65b38f8938b43~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_7add601d116441f682e65b38f8938b43~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_d6402537561543b188afce22850f0a5b~mv2.jpg',
    ],
    description_gr: 'Η χρήση του φίλτρου της Brita Aqua Aroma Crema ενδείκνυται για χρήση σε συνδυασμό με μηχανές καφέ οι οποίες λειτουργούν με ενσωματωμένο δοχείο νερού.',
    description_en: 'This filter is designed for use with coffee machines featuring built-in water reservoirs (suction operation). No additional mounting hardware required for installation.',
    specs: {
      filter_type: 'Carbon',
      capacity_m3: null,
      compatible: 'Coffee machines with specially designed water reservoirs (suction operation)',
      cartridge_sizes: null,
      dimensions_mm: '42.8 x 106.9 x 60.8',
      water_temp_range_c: '4–30',
      max_pressure_bar: null,
    },
    source_url: 'https://www.georgopoulos.com.gr/a-aromacrema',
    status: 'ok',
  },
  {
    id: 'br-proguard',
    name: 'BRITA ProGuard',
    image: 'https://static.wixstatic.com/media/fae23e_ca7abea6de4c47e293aad293cda0d077~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_ca7abea6de4c47e293aad293cda0d077~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_0bf32d3d789841368250c0e8a056314d~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_aab5edc256564a2380d0f3fa837b538c~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_e4a351c50d29498aa6af553b9f37cfd1~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_9ab1f35f42694ce191f0b3b4dc605f4f~mv2.jpg',
    ],
    description_gr: 'Η επίτευξη του ιδανικού αποτελέσματος στο φλιτζάνι αποτελεί κάθε άλλο παρά απλή υπόθεση.',
    description_en: 'An advanced reverse osmosis solution designed to customize beverage characteristics while protecting equipment integrity through salt retention technology (97% filtration rate). Supports up to three filtration stages: pre-filtration, RO membrane, and mineral enrichment.',
    specs: {
      filter_type: 'Reverse Osmosis (RO)',
      capacity_m3: null,
      compatible: 'High-quality espresso machines',
      cartridge_sizes: ['50', '300', '500', '1100'],
      filtration_stages: 3,
      max_pressure_bar: 8.6,
      ph_range: '6.5–7.5',
      dimensions_mm: '366 (W) × 509 (D) × 621 (H)',
      tank_volume_l: 6,
    },
    source_url: 'https://www.georgopoulos.com.gr/brita-proguard',
    status: 'ok',
  },
  {
    id: 'br-puritycquell',
    name: 'BRITA Purity C Quell ST',
    image: 'https://static.wixstatic.com/media/fae23e_d9afd02114ba44eea826b4b01ddb828a~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_d9afd02114ba44eea826b4b01ddb828a~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_512f036980bd49cca9d1c12034513c82~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_3bc29233471140b8b55cbb1866dd2910~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_89e436de08b340078b6ce7d38cdf50a2~mv2.jpg',
    ],
    description_gr: 'Ειδικά σχεδιασμένο για τους τομείς της καφεστίασης και των αυτόματων πωλητών, τo φίλτρο Purity C Quell ST της Brita μειώνει την ανθρακική σκληρότητα στο νερό.',
    description_en: 'Engineered specifically for coffee service and automated vending sectors, this filter reduces carbonate hardness in water while minimizing substances that negatively impact taste and aroma through activated carbon technology.',
    specs: {
      filter_type: 'Ion-exchange resin + Activated Carbon',
      capacity_l: { C150: 2408, C300: 4000, C500: 6800, C1100: 11500 },
      compatible: 'Espresso machines, automatic beverage dispensers',
      cartridge_sizes: ['C150', 'C300', 'C500', 'C1100'],
      max_pressure_bar: 8.6,
      installation: 'Vertical or horizontal',
    },
    source_url: 'https://www.georgopoulos.com.gr/puritycquellst',
    status: 'ok',
  },
  {
    id: 'br-puritycfin',
    name: 'BRITA Purity C Finest',
    image: 'https://static.wixstatic.com/media/fae23e_6a35c3a3e6ad476796c0ec438603c94e~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_6a35c3a3e6ad476796c0ec438603c94e~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_acba848f3cae4f278b57cfdf1148b957~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_3bc29233471140b8b55cbb1866dd2910~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_1107faca97b5467c88dbbed9b011e0b6~mv2.png',
    ],
    description_gr: 'Το φίλτρο Brita Purity C Finest, με τη μοναδική του σύνθεση απελευθερώνει το ξεχωριστό άρωμα του κάθε espresso.',
    description_en: 'The BRITA Purity C Finest filter enhances espresso\'s distinctive aroma through its unique composition, utilizing ion-exchange resin to combat water hardness and activated carbon to eliminate substances that negatively affect taste and aroma.',
    specs: {
      filter_type: 'Ion-exchange resin + Activated Carbon',
      capacity_l: { C150: 1100, C300: 1800, C500: 3414, C1100: 6000 },
      compatible: 'Espresso machines with water tanks',
      cartridge_sizes: ['C150', 'C300', 'C500', 'C1100'],
      max_pressure_bar: 8.6,
      hardness_reduction_dh: 10,
      installation: 'Vertical',
    },
    source_url: 'https://www.georgopoulos.com.gr/purityfinestc',
    status: 'ok',
  },
  {
    id: 'br-purityc50',
    name: 'BRITA Purity C50 Fresh',
    image: 'https://static.wixstatic.com/media/fae23e_0768dccb43fc4320a5fec88bd978210a~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_0768dccb43fc4320a5fec88bd978210a~mv2.jpg',
    ],
    description_gr: 'Ενεργός Άνθρακας. Απομάκρυνση όλων των στοιχείων που επηρεάζουν αρνητικά τη γεύση και το άρωμα.',
    description_en: 'Active carbon filtration that eliminates all substances negatively impacting taste and aroma characteristics. Designed for automatic beverage dispensers and drinking water filtration systems.',
    specs: {
      filter_type: 'Activated Carbon',
      capacity_m3: null,
      compatible: 'Automatic beverage dispensers, drinking water filtration systems',
      cartridge_sizes: null,
      max_pressure_bar: null,
    },
    source_url: 'https://www.georgopoulos.com.gr/brita',
    status: 'ok',
  },
  {
    id: 'br-purityquell',
    name: 'BRITA Purity Quell ST',
    image: 'https://static.wixstatic.com/media/fae23e_8eec5a44ba8b4869a193dc2332794b47~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_8eec5a44ba8b4869a193dc2332794b47~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_456bf8159d7d4bbe93822d5fc4f12c95~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_2fbd60b2c5e348e6ab6ad43af3b58df3~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_e0b253b2756e4e8ab54df57f49855914~mv2.jpg',
    ],
    description_gr: 'Η σειρά PURITY Quell ST της BRITA αποτελεί την ιδανική επιλογή γι\' αυτούς οι οποίοι επιθυμούν να πληρούν τα υψηλότερα πρότυπα ποιότητας.',
    description_en: 'The BRITA PURITY Quell ST series is the ideal choice for those seeking the highest quality standards. Combats water hardness and particulates creating unpleasant taste and odor in espresso. Specialty resin for carbonate hardness reduction, with activated carbon and fleece pre/post-filtration.',
    specs: {
      filter_type: 'Ion-exchange resin + Activated Carbon',
      capacity_l: { size_1200: 13187 },
      compatible: 'Espresso machines, automatic beverage dispensers',
      cartridge_sizes: ['1200'],
      max_pressure_bar: 6.9,
      installation: 'Vertical or horizontal',
    },
    source_url: 'https://www.georgopoulos.com.gr/purityquell',
    status: 'ok',
  },
  {
    id: 'br-puritycsteam',
    name: 'BRITA Purity C Steam',
    image: 'https://static.wixstatic.com/media/fae23e_d1cc18cec1874009a4e2c1fe0af0c484~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_d1cc18cec1874009a4e2c1fe0af0c484~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_90367a896d204e0da4d83848bf993302~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_3bc29233471140b8b55cbb1866dd2910~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_b28eead7d06c47f2b651a988dc81c2d8~mv2.png',
    ],
    description_gr: 'Το φίλτρο Purity Steam της BRITA αφαιρεί από το νερό τα επιβλαβή κατιόντα του Ασβεστίου (Ca+) και του Μαγνησίου (Mg+) ενώ ταυτόχρονα συγκρατεί μέταλλα όπως ο μόλυβδος και ο χαλκός.',
    description_en: 'The Purity C Steam filter removes harmful calcium (Ca+) and magnesium (Mg+) ions while also retaining metals such as lead and copper. Delivers enhanced flow rates with minimal pressure loss for continuous operation of combi-type ovens.',
    specs: {
      filter_type: 'Ion-exchange resin + Activated Carbon (multi-stage)',
      capacity_l: { C500: 4675, C1100: 7907 },
      compatible: 'Combi steamers, spray-type ovens, boiler-system ovens',
      cartridge_sizes: ['C500', 'C1100'],
      flow_rate_l_per_h: 300,
      max_pressure_bar: 8.6,
      installation: '3-stage filter head',
    },
    source_url: 'https://www.georgopoulos.com.gr/puritycsteam',
    status: 'ok',
  },
  {
    id: 'br-puritysteam',
    name: 'BRITA Purity Steam',
    image: 'https://static.wixstatic.com/media/fae23e_e11b15aedc434eb48ea548923f920549~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_e11b15aedc434eb48ea548923f920549~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_bee9cfc1c0e440e18209f0d84a792e59~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_2087187c1e1c43be89ed7d23a9d4099e~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_e0b253b2756e4e8ab54df57f49855914~mv2.jpg',
    ],
    description_gr: 'Το φίλτρο Purity Steam της BRITA αφαιρεί από το νερό τα επιβλαβή κατιόντα του Ασβεστίου (Ca+) και του Μαγνησίου (Mg+).',
    description_en: 'The Purity Steam filter removes harmful calcium and magnesium ions from water, enabling uninterrupted operation of combi-type ovens through increased flow and minimal pressure loss.',
    specs: {
      filter_type: 'Ion-exchange resin + fleece pre/post-filtration',
      capacity_l: { size_1200: 10800 },
      compatible: 'Combi steamers, spray ovens, boiler-type ovens',
      cartridge_sizes: ['1200'],
      flow_rate_l_per_h: 500,
      max_pressure_bar: 6.9,
      installation: 'Vertical or horizontal',
    },
    source_url: 'https://www.georgopoulos.com.gr/puritysteam',
    status: 'ok',
  },
  {
    id: 'br-purityclean',
    name: 'BRITA Purity Clean',
    image: 'https://static.wixstatic.com/media/fae23e_b18894ab64d643be8078b431b77eeb7e~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_b18894ab64d643be8078b431b77eeb7e~mv2.jpg',
    ],
    description_gr: 'Το φίλτρο Purity Clean της BRITA αποτελεί την ιδανική επιλογή για χρήση στα επαγγελματικά πλυντήρια πιάτων και ποτηριών.',
    description_en: 'The BRITA Purity Clean filter is the ideal choice for professional dishwashers and glasswashers. Uses partial metal ion removal to eliminate salt-causing ions and microparticles.',
    specs: {
      filter_type: 'Resin (partial metal ion removal)',
      capacity_l: 12000,
      compatible: 'Professional dishwashers and glasswashers',
      cartridge_sizes: null,
      max_pressure_bar: 6,
      installation: 'Vertical or horizontal',
    },
    source_url: 'https://www.georgopoulos.com.gr/purityclean',
    status: 'ok',
  },
  {
    id: 'br-puritycleanex',
    name: 'BRITA Purity Clean Extra',
    image: 'https://static.wixstatic.com/media/fae23e_ba8b5ab7d4334e07802751ce14a85a45~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_b18894ab64d643be8078b431b77eeb7e~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_ba8b5ab7d4334e07802751ce14a85a45~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_e0b253b2756e4e8ab54df57f49855914~mv2.jpg',
    ],
    description_gr: 'Η χρήση του κρίνεται απαραίτητη για είδη κουζίνας και γυαλικά πολύ υψηλής ποιότητας.',
    description_en: 'Essential for high-end kitchenware and premium glassware applications. Uses total metal ion removal technology (multi-stage resin) to eliminate salt-causing elements and water marks.',
    specs: {
      filter_type: 'Resin (total metal ion removal, multi-stage)',
      capacity_l: 5000,
      compatible: 'Professional dishwashers and glasswashers (premium/high-end)',
      cartridge_sizes: null,
      max_pressure_bar: 6,
      installation: 'Vertical or horizontal',
    },
    source_url: 'https://www.georgopoulos.com.gr/puritycleanextra',
    status: 'ok',
  },
  {
    id: 'br-purityc1000',
    name: 'BRITA Purity C1000 AC',
    image: 'https://static.wixstatic.com/media/fae23e_597b50166df1459ab03884c74fffffb9~mv2.jpg',
    images: [
      'https://static.wixstatic.com/media/fae23e_597b50166df1459ab03884c74fffffb9~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_67e07d0ba6304fb8b4863e80f88d3b98~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_7bc9e9c475d045d0a71c5e2f56d86a8a~mv2.jpg',
      'https://static.wixstatic.com/media/fae23e_1107faca97b5467c88dbbed9b011e0b6~mv2.png',
    ],
    description_gr: 'Χάρις στο block ενεργού άνθρακα, το BRITA Purity C1000 AC συγκρατεί όλα εκείνα τα στοιχεία που επηρεάζουν αρνητικά τη γεύση, το άρωμα και την εμφάνιση του νερού.',
    description_en: 'Using an activated carbon block, the BRITA Purity C1000 AC retains all substances that negatively affect taste, aroma, and water appearance, delivering superior beverage quality.',
    specs: {
      filter_type: 'Activated Carbon (dual-stage)',
      capacity_m3: null,
      compatible: 'Coffee machines with water reservoirs',
      cartridge_sizes: null,
      particle_filtration_micron: 0.5,
      nsf_standard: '42',
      bypass: '0%',
      features: 'Quick-replacement system, built-in sampling valve',
    },
    source_url: 'https://www.georgopoulos.com.gr/purityc1000-ac',
    status: 'ok',
  },
];
